### ISSUE TITLE
Add question also in chat log

### ISSUE THREAD

**Issue by piyush-gangrade** [bacloud23/Highest-priest-GPT#12]
Title:
[BUG] Questioner's Questions Not Displayed in Chat Log

Description:
In the "Highest Priest GPT" game, when the questioner asks a question, it does not appear in the chat log. Currently, only the responder's answers are visible. This functionality is crucial for maintaining an engaging conversation and providing context to the players.

Current Behavior:

The questioner asks a question.
The responder provides an answer.
Only the responder's answer is shown in the chat log, while the question is missing.
Expected Behavior:

When the questioner asks a question, it should be displayed in the chat log along with the responder's answer, allowing for a complete conversation record.

![Screenshot 2024-10-12 013142](https://github.com/user-attachments/assets/26fc7980-750a-488b-971d-fa390e91149b)

Please assign this to me.

**Comment by bacloud23** [comment]
@piyush-gangrade do you even understand the idea of the app ?!
I do not like gpt generated contributions.

**Comment by piyush-gangrade** [comment]
@bacloud23  I understand how the app works. When the responder answers a question and a new one is asked, the previous question isn't saved anywhere. This makes it hard for the responder to refer back to previous answers if there are follow-up questions.

Also, when the questioner submits a question by clicking "Ask Question," it's unclear if the question was submitted because it doesn't appear anywhere. To fix this, the question should show up in the chat log as soon as it's asked, so the questioner knows it was submitted successfully.

Lastly, I use GPT only to present my ideas more clearly and understandably.

**Comment by bacloud23** [comment]
The questioner needs not to know even the existence of the questioner, this is the whole fun game !
