### ISSUE TITLE
Add "Copy" button for shareable link

### ISSUE THREAD

**Issue by SSShogunn** [bacloud23/Highest-priest-GPT#18]
We need to add a "Copy" button next to the shareable link generated for questioners. This will improve user experience by allowing easy copying of the link to the clipboard.

can you assign me this issue??

**Comment by SSShogunn** [comment]
can you add the hacktoberfest tag too ??

**Comment by bacloud23** [comment]
I did not ask for this issue to begin with. This is a regular contribution that I thank you for :)
