### ISSUE TITLE
Unnecessary Box Should Be Replaced by Password Input Field

### ISSUE THREAD

**Issue by ayushsingh199** [bacloud23/Highest-priest-GPT#29]
#### Description
There is an unnecessary box being used in place of a password input field. This should be replaced with a proper password input box to improve the user experience and functionality, such as masking the password when typing.

#### Expected Behavior
A password input box should be used instead of the current generic box. The password box should:
- Mask the password characters as the user types.
- Allow for additional features like a "show password" option (eye icon).

#### Actual Behavior
A generic box is used where a password input field should be, leading to:
- No password masking.
- Incorrect input field type for passwords.

#### Steps to Reproduce
1. Open the page containing the box for password input.
2. Try typing into the box (it does not behave as a password input field).
3. Notice that password characters are not masked
 and the input box is of the wrong type.
<img width="654" alt="Screenshot 2024-10-15 at 7 25 52 PM" src="https://github.com/user-attachments/assets/2134d493-f87e-4c78-9ea0-7c158f48f9a2">

**Comment by ayushsingh199** [comment]
please assign me this issue!

**Comment by bacloud23** [comment]
There is no password. If you do not restrain from proposing unrelated GPT generated ideas. I'll block you from contributing.
What password are you talking about ?
