### ISSUE TITLE
Rate Limiting for Messages

### ISSUE THREAD

**Issue by bacloud23** [bacloud23/Highest-priest-GPT#6]
**Issue:** There's no rate limiting for sending messages, so a malicious user could potentially spam the channel with questions or answers.

**Improvement:** Implement rate limiting to prevent spamming by restricting the number of messages a user can send within a certain timeframe.

**Comment by Mang0codes** [comment]
working on this

**Comment by yazdanhaider** [comment]
Hey @bacloud23 could you please assign me this task i almost solve the issue.

<img width="1100" alt="Screenshot 2024-10-12 at 12 48 27 AM" src="https://github.com/user-attachments/assets/8bc83d1e-530b-4765-a2e1-2b6bc0933f2e">
